# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Life Cycle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   pod 'SnapKit', '~> 5.0.0'

  target 'Life CycleTests' do
    inherit! :search_paths
    pod 'SnapKit', '~> 5.0.0'
  end

  target 'Life CycleUITests' do
    pod 'SnapKit', '~> 5.0.0'
  end

end

target 'Life Cycle 2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '~> 5.0.0'

end
